apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-backstage-service
  annotations:
    github.com/project-slug: susanta2022/dev-backstage-service
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: susanta@adansa.com

  
